### ISSUE TITLE
Cannot find module 'xml-escape'

### ISSUE THREAD

**Issue by aerohub** [owen8877/hexo-generator-podcast#1]
Hello there!
I get this on `hexo s` command

```
ERROR Plugin load failed: hexo-generator-podcast
Error: Cannot find module 'xml-escape'
```

Will you help me, please?

**Comment by owen8877** [comment]
Please install that dependency manually for the time being. I'll update `package.json` in time.

**Comment by owen8877** [comment]
Dependencies in `package.json` have been updated.
Please run with `npm i`.
